version: 2.1
jobs:
  build:
    docker:
      - image: node:lts-browsers
    steps:
      - checkout
      - run:
          name: Install NPM Packages
          command: |
            npm install
      - run:
          name: Build
          command: |
            npm run build
      - run:
          name: Style Check
          command: |
            npm run style
      - run:
          name: Lint Check
          command: |
            npm run lint
      - run:
          name: Unit Tests
          command: |
            npm run test:nowatch
