version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - checkout
      - run:
          name: Build
          command: |
            npm run build
      - run:
          name: Style Check
          command: |
            npm run style
      - run:
          name: Lint Check
          command: |
            npm run lint
